PACKAGE_MANAGER = cargo
RUN_COMMAND = run
BUILD_COMMAND = build
TEST_COMMAND = test
FMT_COMMAND = fmt
CLIPPY_COMMAND = CLIPPY

ASM_FILE = test.asm
MVM_FILE = test.mvm
ASM_ARGS = 
CODE_EDITOR = nvim

run:
	$(CODE_EDITOR) $(ASM_FILE)
	$(PACKAGE_MANAGER) $(RUN_COMMAND) -- compile $(ASM_FILE) $(ASM_ARGS)
	$(PACKAGE_MANAGER) $(RUN_COMMAND) -- run $(MVM_FILE)
